version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/SportsMeetApplication

permissions:
  - object: /home/ec2-user/SportsMeetApplication
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/python_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/nginx.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/gunicorn.sh  # 🔹 Move Gunicorn startup here
      timeout: 300
      runas: ec2-user
    - location: scripts/restart_gunicorn.sh
      timeout: 60
      runas: ec2-user
  
