version: 0.2  # ✅ Correct version

phases:
  install:
    runtime-versions:
      python: 3.8  # ✅ Set Python version (change as needed)
  
  pre_build:
    commands:
      - echo "Pre-build operations started..."
      - python -m pip install --upgrade pip  # ✅ Ensure latest pip
      - python -m pip install -r requirements.txt  # ✅ More reliable way to install dependencies

  build:
    commands:
      - echo "Building the application..."
  
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'  # ✅ Matches all files
