version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Updating system packages..."
      - apt update && apt upgrade -y
      - echo "Installing PostgreSQL development packages..."
      - apt install -y libpq-dev gcc python3-dev
      - echo "Ensuring Python 3.11 is globally set..."
      - if ! pyenv versions | grep -q '3.11'; then pyenv install 3.11; fi
      - pyenv global 3.11
      - python -m pip install --upgrade pip

  build:
    commands:
      - echo "Installing dependencies..."
      - pip install psycopg2-binary  # ✅ Use precompiled binary package
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
