version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Updating system packages..."
      - apt update && apt upgrade -y
      - echo "Installing PostgreSQL development packages..."
      - apt install -y libpq-dev gcc python3-dev
      - echo "Ensuring Python 3.11 is globally set..."
      - python -m pip install --upgrade pip

build:
  commands:
    - echo "Checking current directory..."
    - pwd  # ✅ Print current working directory
    - echo "Listing files..."
    - ls -lah  # ✅ List all files
    - echo "Installing dependencies..."
    - pip install -r requirements.txt  # ✅ Install dependencies

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
