# Generated by Django 5.1.6 on 2025-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0002_alter_court_sport_alter_court_venue_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
