# Generated by Django 5.1.6 on 2025-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0013_courtrequest_created_at_alter_court_court_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='CourtRequest',
        ),
    ]
