# Generated by Django 5.1.6 on 2025-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0015_courtrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mode_of_pyment',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'offline')], default='online', max_length=10),
        ),
    ]
