# Generated by Django 5.1.6 on 2025-03-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0023_booking_booking_id_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Final Price'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Coupon Code')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value (₹)')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Usage')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='Current Usage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='SportMeetApp.venue', verbose_name='Venue')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportMeetApp.coupon', verbose_name='Coupon'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Discount Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage')], default='percentage', max_length=10, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Value (%)')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Usage')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='Current Usage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='SportMeetApp.venue', verbose_name='Venue')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportMeetApp.discount', verbose_name='Discount'),
        ),
    ]
