# Generated by Django 5.1.6 on 2025-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0006_court_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtrequest',
            name='duration',
            field=models.PositiveIntegerField(choices=[(30, '30 Minutes'), (60, '1 Hour'), (90, '1 Hour 30 Minutes'), (120, '2 Hours')], default=30),
        ),
    ]
