# Generated by Django 5.1.6 on 2025-03-13 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0011_cancellationandrefund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='end_time',
            field=models.TimeField(verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='SportMeetApp.venueownerprofile', verbose_name='Venue Owner'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_time',
            field=models.TimeField(verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='venueownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Venue profile'),
        ),
    ]
