# Generated by Django 5.1.6 on 2025-03-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0014_alter_court_court_number_delete_courtrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.PositiveIntegerField(choices=[(30, '30 Minutes'), (60, '1 Hour'), (90, '1 Hour 30 Minutes'), (120, '2 Hours')], default=30)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeetApp.sporttype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeetApp.venue')),
            ],
        ),
    ]
