# Generated by Django 5.1.6 on 2025-03-15 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0016_booking_mode_of_pyment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='end_time',
            field=models.TimeField(verbose_name='Closing Hours'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Venue Name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_time',
            field=models.TimeField(verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='venueownerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='venueownerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile'),
        ),
    ]
