# Generated by Django 5.1.6 on 2025-03-18 11:04

import SportMeetApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0018_rename_status_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mode_of_pyment',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'offline')], default='online', max_length=10, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='venueownerprofile',
            name='id',
            field=models.PositiveIntegerField(default=SportMeetApp.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
