# Generated by Django 5.1.6 on 2025-03-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0019_alter_booking_mode_of_pyment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='venueownerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile'),
        ),
    ]
