# Generated by Django 5.1.6 on 2025-03-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0021_booking_manual_name_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mode_of_pyment',
            new_name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='manual_name',
        ),
    ]
