# Generated by Django 5.1.6 on 2025-03-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0025_couponusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        # migrations.RemoveField(
        #     model_name='couponusage',
        #     name='coupon',
        # ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_price',
        ),
        migrations.AddField(
            model_name='venue',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
