# Generated by Django 5.1.6 on 2025-03-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0027_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='discount',
        ),
    ]
