# Generated by Django 5.1.6 on 2025-03-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0012_rating_owner_reply_rating_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='courtrequest',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_requests', to='SportMeetApp.sporttype'),
        ),
        migrations.AlterField(
            model_name='courtrequest',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_requests', to='SportMeetApp.venue'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Venue Response'),
        ),
    ]
