# Generated by Django 5.1.6 on 2025-03-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0017_alter_customerprofile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='booking_status',
        ),
    ]
