# Generated by Django 5.1.6 on 2025-03-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeetApp', '0020_alter_customerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manual Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='SportMeetApp.customerprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mode_of_pyment',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10, verbose_name='Mode of Payment'),
        ),
    ]
